Remove useless path.join()
electron/electron-api-demos pull request #473
Opened 2020-11-24 13:51 UTC by Joao-Pedro-S

2020-12-07 17:45 UTC, mjguidry68 approved these changes

2020-12-08 10:03 UTC, MikeyMJCO commented
@J-P-S-O you need to edit your commit message to something like `fix: Remove useless path.join()`

2020-12-08 12:54 UTC, J-P-S-O commented
> @J-P-S-O you need to edit your commit message to something like `fix: Remove useless path.join()` This will allow the PR to pass the Semantic Pull Request check.

Ok thank you.

2020-12-08 12:55 UTC, J-P-S-O commented
@MikeyMJCO how can a new check be triggered?

2020-12-09 19:50 UTC, yanmyonain31 requested changes
I want to use

2020-12-10 22:50 UTC, codebytere commented
@J-P-S-O you need to edit the commit itself since there's only one commit, not just the title.

2020-12-13 19:27 UTC, singh-ravi-siso commented
..

2021-04-23 12:30 UTC, MoneyMajor approved these changes

2021-12-02 20:11 UTC, J-P-S-O commented
I can't edit the commit because i deleted the original fork :(

2026-08-02 07:50 UTC, MarshallOfSound commented
Closing this out: `electron/electron-api-demos` has been archived and is no longer maintained, so this pull request can't be merged. Apologies that it sat without a response — thank you for taking the time to contribute.

2026-08-02 07:50 UTC, closed without merging